// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	authapi "lina-core/api/auth"
	authsvc "lina-core/internal/service/auth"
	"lina-core/internal/service/bizctx"
	configsvc "lina-core/internal/service/config"
)

// ControllerV1 is the authentication controller.
type ControllerV1 struct {
	authSvc   authsvc.Service   // auth service
	bizCtxSvc bizctx.Service    // business context service
	configSvc configsvc.Service // host config for workspace base path
}

// NewV1 creates and returns a new authentication controller instance.
func NewV1(authSvc authsvc.Service, bizCtxSvc bizctx.Service, configSvc configsvc.Service) authapi.IAuthV1 {
	return &ControllerV1{
		authSvc:   authSvc,
		bizCtxSvc: bizCtxSvc,
		configSvc: configSvc,
	}
}
