// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-content-notice/backend/internal/dao/internal"
)

// noticeDao is the data access object for the table plugin_linapro_content_notice.
// You can define custom methods on it to extend its functionality as needed.
type noticeDao struct {
	*internal.NoticeDao
}

var (
	// Notice is a globally accessible object for table plugin_linapro_content_notice operations.
	Notice = noticeDao{internal.NewNoticeDao()}
)

// Add your custom methods and functionality below.
