// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-tenant-core/backend/internal/dao/internal"
)

// configOverrideDao is the data access object for the table plugin_linapro_tenant_core_config_override.
// You can define custom methods on it to extend its functionality as needed.
type configOverrideDao struct {
	*internal.ConfigOverrideDao
}

var (
	// ConfigOverride is a globally accessible object for table plugin_linapro_tenant_core_config_override operations.
	ConfigOverride = configOverrideDao{internal.NewConfigOverrideDao()}
)

// Add your custom methods and functionality below.
