// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-tenant-core/backend/internal/dao/internal"
)

// tenantDao is the data access object for the table plugin_linapro_tenant_core_tenant.
// You can define custom methods on it to extend its functionality as needed.
type tenantDao struct {
	*internal.TenantDao
}

var (
	// Tenant is a globally accessible object for table plugin_linapro_tenant_core_tenant operations.
	Tenant = tenantDao{internal.NewTenantDao()}
)

// Add your custom methods and functionality below.
