// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-tenant-core/backend/internal/dao/internal"
)

// userMembershipDao is the data access object for the table plugin_linapro_tenant_core_user_membership.
// You can define custom methods on it to extend its functionality as needed.
type userMembershipDao struct {
	*internal.UserMembershipDao
}

var (
	// UserMembership is a globally accessible object for table plugin_linapro_tenant_core_user_membership operations.
	UserMembership = userMembershipDao{internal.NewUserMembershipDao()}
)

// Add your custom methods and functionality below.
