// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-demo-source/backend/internal/dao/internal"
)

// recordDao is the data access object for the table plugin_linapro_demo_source_record.
// You can define custom methods on it to extend its functionality as needed.
type recordDao struct {
	*internal.RecordDao
}

var (
	// Record is a globally accessible object for table plugin_linapro_demo_source_record operations.
	Record = recordDao{internal.NewRecordDao()}
)

// Add your custom methods and functionality below.
