import Banner from "@douyinfe/semi-ui/lib/es/banner";
import Button from "@douyinfe/semi-ui/lib/es/button";
import Card from "@douyinfe/semi-ui/lib/es/card";
import Checkbox from "@douyinfe/semi-ui/lib/es/checkbox";
import { Form } from "@douyinfe/semi-ui/lib/es/form";
import Input from "@douyinfe/semi-ui/lib/es/input";
import Modal from "@douyinfe/semi-ui/lib/es/modal";
import Space from "@douyinfe/semi-ui/lib/es/space";
import Table from "@douyinfe/semi-ui/lib/es/table";
import type { ColumnProps } from "@douyinfe/semi-ui/lib/es/table/interface";
import Tag from "@douyinfe/semi-ui/lib/es/tag";
import Toast from "@douyinfe/semi-ui/lib/es/toast";
import Typography from "@douyinfe/semi-ui/lib/es/typography";
import { MobileRecordActions, MobileRecordCard, MobileRecordField, MobileRecordFields, MobileRecordList, MobileRecordTitle, ResponsiveListFeedback, useLinaPluginHost } from "@linapro/plugin-ui";
import { useCallback, useEffect, useMemo, useState } from "react";

import { createAiCoreApi, type Invocation, type InvocationListParams } from "./ai-client";
import { capabilityTypeLabel, formatLatencyMs, formatTimestamp, hasPermission, joinCapabilityMethod, protocolLabel, tierCapabilityTypeKeys, tierCodeLabel } from "./ai-data";
import { InvocationDetailSideSheet } from "./invocation-detail-side-sheet";
import "./ai-core.css";

interface SearchValues extends InvocationListParams { endedAtInput?: string; startedAtInput?: string }
function timestamp(value?: string): number | undefined { if (!value) return undefined; const output = new Date(value).getTime(); return Number.isFinite(output) ? output : undefined; }

export default function InvocationLogs() {
  const host = useLinaPluginHost(); const api = useMemo(() => createAiCoreApi(host.api), [host.api]); const [params, setParams] = useState<InvocationListParams>({ pageNum: 1, pageSize: 10 }); const [rows, setRows] = useState<Invocation[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(false); const [listError, setListError] = useState<string>(); const [detail, setDetail] = useState<Invocation>(); const [cleanOpen, setCleanOpen] = useState(false); const [deleteAll, setDeleteAll] = useState(false); const [startedAt, setStartedAt] = useState(""); const [endedAt, setEndedAt] = useState(""); const [cleaning, setCleaning] = useState(false);
  const load = useCallback(async () => { setLoading(true); setListError(undefined); try { const result = await api.invocationList(params); setRows(result.items); setTotal(result.total); } catch (error) { setListError(error instanceof Error ? error.message : String(error)); } finally { setLoading(false); } }, [api, params]); useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  function search(values: SearchValues) { const { endedAtInput, startedAtInput, ...filters } = values; setParams({ ...filters, endedAt: timestamp(endedAtInput), pageNum: 1, pageSize: params.pageSize, startedAt: timestamp(startedAtInput) }); }
  async function clean() { const range = { endedAt: timestamp(endedAt), startedAt: timestamp(startedAt) }; if (!deleteAll && (!range.startedAt || !range.endedAt)) { Toast.warning(host.t("plugin.linapro-ai-core.invocation.messages.deleteRangeRequired")); return; } setCleaning(true); try { const result = await api.invocationClean(deleteAll ? undefined : range); Toast.success(host.t("plugin.linapro-ai-core.invocation.messages.deleteRangeSuccess", { count: result.deleted })); setCleanOpen(false); await load(); } finally { setCleaning(false); } }
  function renderActions(row: Invocation) { return <Button onClick={() => setDetail(row)} theme="borderless">{host.t("plugin.linapro-ai-core.common.detail")}</Button>; }
  const columns: ColumnProps<Invocation>[] = [
    { dataIndex: "purpose", title: host.t("plugin.linapro-ai-core.invocation.fields.purpose"), width: 180 }, { dataIndex: "capabilityMethod", render: (_, row) => joinCapabilityMethod(row.capabilityType, row.capabilityMethod), title: host.t("plugin.linapro-ai-core.invocation.fields.method"), width: 180 }, { dataIndex: "protocol", render: (value) => protocolLabel(String(value)), title: host.t("plugin.linapro-ai-core.model.fields.protocol"), width: 130 },
    { dataIndex: "sourcePluginId", title: host.t("plugin.linapro-ai-core.invocation.fields.sourcePluginId"), width: 180 }, { dataIndex: "tierCode", render: (value) => value ? tierCodeLabel(host.t, String(value)) : "-", title: host.t("plugin.linapro-ai-core.invocation.fields.tierCode"), width: 110 },
    { dataIndex: "status", render: (value) => <Tag color={value === "success" ? "green" : "red"}>{host.t(value === "success" ? "plugin.linapro-ai-core.common.success" : "plugin.linapro-ai-core.common.failed")}</Tag>, title: host.t("plugin.linapro-ai-core.invocation.fields.status"), width: 100 }, { dataIndex: "providerName", title: host.t("plugin.linapro-ai-core.invocation.fields.providerName"), width: 150 }, { dataIndex: "modelName", title: host.t("plugin.linapro-ai-core.invocation.fields.modelName"), width: 180 },
    { dataIndex: "latencyMs", render: (value) => <span className="ai-core-mono">{formatLatencyMs(Number(value))}</span>, title: host.t("plugin.linapro-ai-core.invocation.fields.latencyMs"), width: 110 }, { dataIndex: "inputTokens", render: (_, row) => `${row.inputTokens} / ${row.outputTokens}`, title: host.t("plugin.linapro-ai-core.invocation.fields.tokens"), width: 120 }, { dataIndex: "createdAt", render: (value) => formatTimestamp(Number(value), host.locale), title: host.t("pages.common.createdAt"), width: 190 },
    { fixed: "right", render: (_, row) => renderActions(row), title: host.t("pages.common.actions"), width: 100 },
  ];
  return <section className="ai-core-page" data-testid="ai-invocation-logs-page">
    <header className="ai-core-page-header"><Typography.Title heading={3}>{host.t("plugin.linapro-ai-core.invocation.tableTitle")}</Typography.Title></header>
    <Card><Form<SearchValues> className="ai-core-search-form" id="ai-invocation-filter-form" layout="horizontal" onSubmit={search}><Form.Select field="capabilityType" id="ai-invocation-filter-capability-type" label={host.t("plugin.linapro-ai-core.capability.type")} optionList={tierCapabilityTypeKeys.map((type) => ({ label: capabilityTypeLabel(host.t, type), value: type }))} /><Form.Input field="capabilityMethod" id="ai-invocation-filter-method" label={host.t("plugin.linapro-ai-core.invocation.fields.method")} /><Form.Input field="purpose" id="ai-invocation-filter-purpose" label={host.t("plugin.linapro-ai-core.invocation.fields.purpose")} /><Form.Select field="tierCode" id="ai-invocation-filter-tier" label={host.t("plugin.linapro-ai-core.invocation.fields.tierCode")} optionList={["basic", "standard", "advanced"].map((code) => ({ label: tierCodeLabel(host.t, code), value: code }))} /><Form.Select field="status" id="ai-invocation-filter-status" label={host.t("plugin.linapro-ai-core.invocation.fields.status")} optionList={[{ label: host.t("plugin.linapro-ai-core.common.success"), value: "success" }, { label: host.t("plugin.linapro-ai-core.common.failed"), value: "failed" }]} /><Form.Input field="sourcePluginId" id="ai-invocation-filter-source-plugin" label={host.t("plugin.linapro-ai-core.invocation.fields.sourcePluginId")} /><Form.Input field="startedAtInput" id="ai-invocation-filter-start-time" label={host.t("plugin.linapro-ai-core.common.startTime")} type="datetime-local" /><Form.Input field="endedAtInput" id="ai-invocation-filter-end-time" label={host.t("plugin.linapro-ai-core.common.endTime")} type="datetime-local" /><Button htmlType="submit" theme="solid" type="primary">{host.t("pages.common.search")}</Button></Form></Card>
    <Card>
      <div className="ai-core-toolbar"><Space>{hasPermission(host.permissions, "ai:invocation:clear") ? <Button data-testid="ai-invocation-clear" onClick={() => { setDeleteAll(false); setStartedAt(""); setEndedAt(""); setCleanOpen(true); }} type="danger">{host.t("pages.common.delete")}</Button> : null}</Space></div>
      <ResponsiveListFeedback empty={!rows.length} emptyLabel={host.t("pages.common.emptyList")} error={Boolean(listError)} errorDetail={listError} errorLabel={host.t("pages.common.loadFailed")} loading={loading} loadingLabel={host.t("pages.common.loading")} onRetry={() => void load()} retryLabel={host.t("fallback.retry")} testId="ai-invocation-list-feedback" />
      {!loading && !listError && rows.length ? <>
        <div className="responsive-desktop-table" data-testid="ai-invocation-table"><Table<Invocation> columns={columns} dataSource={rows} pagination={{ currentPage: params.pageNum, onChange: (pageNum) => setParams((current) => ({ ...current, pageNum })), pageSize: params.pageSize, total }} rowKey="id" scroll={{ x: 1750 }} /></div>
        <MobileRecordList testId="ai-invocation-mobile-list">{rows.map((row) => <MobileRecordCard key={row.id} testId={`ai-invocation-mobile-card-${row.id}`}><MobileRecordTitle>{row.purpose || row.requestId}</MobileRecordTitle><MobileRecordFields><MobileRecordField label={host.t("plugin.linapro-ai-core.invocation.fields.method")} value={joinCapabilityMethod(row.capabilityType, row.capabilityMethod)} /><MobileRecordField label={host.t("plugin.linapro-ai-core.invocation.fields.status")} value={<Tag color={row.status === "success" ? "green" : "red"}>{host.t(row.status === "success" ? "plugin.linapro-ai-core.common.success" : "plugin.linapro-ai-core.common.failed")}</Tag>} /><MobileRecordField label={host.t("plugin.linapro-ai-core.invocation.fields.providerName")} value={`${row.providerName || "-"} / ${row.modelName || "-"}`} /><MobileRecordField label={host.t("plugin.linapro-ai-core.invocation.fields.latencyMs")} value={formatLatencyMs(row.latencyMs)} /><MobileRecordField label={host.t("pages.common.createdAt")} value={formatTimestamp(row.createdAt, host.locale)} /></MobileRecordFields><MobileRecordActions>{renderActions(row)}</MobileRecordActions></MobileRecordCard>)}</MobileRecordList>
      </> : null}
    </Card>
    <InvocationDetailSideSheet locale={host.locale} onClose={() => setDetail(undefined)} open={Boolean(detail)} record={detail} t={host.t} />
    <Modal footer={<Space><Button onClick={() => setCleanOpen(false)}>{host.t("pages.common.cancel")}</Button><Button loading={cleaning} onClick={() => void clean()} theme="solid" type="danger">{host.t("pages.common.confirm")}</Button></Space>} onCancel={() => setCleanOpen(false)} title={host.t("plugin.linapro-ai-core.invocation.messages.deleteRangeTitle")} visible={cleanOpen} width="min(520px, calc(100vw - 24px))"><div data-testid="ai-invocation-delete-alert"><Banner description={host.t("plugin.linapro-ai-core.invocation.messages.deleteRangeDescription")} type="warning" /></div><div data-testid="ai-invocation-delete-all-option" style={{ marginTop: 16 }}><Checkbox checked={deleteAll} onChange={(event) => setDeleteAll(Boolean(event.target.checked))}>{host.t("plugin.linapro-ai-core.invocation.messages.deleteAllLabel")}</Checkbox><Typography.Paragraph type="tertiary">{host.t("plugin.linapro-ai-core.invocation.messages.deleteAllHint")}</Typography.Paragraph></div><div data-testid="ai-invocation-delete-range-section"><Space vertical><Input aria-label={host.t("plugin.linapro-ai-core.common.startTime")} disabled={deleteAll} onChange={setStartedAt} type="datetime-local" value={startedAt} /><Input aria-label={host.t("plugin.linapro-ai-core.common.endTime")} disabled={deleteAll} onChange={setEndedAt} type="datetime-local" value={endedAt} /></Space></div></Modal>
  </section>;
}
