import {
  IconActivity,
  IconAIStrokedLevel1,
  IconApps,
  IconArticle,
  IconBeaker,
  IconBox,
  IconBriefcase,
  IconCalendarStroked,
  IconClockStroked,
  IconCode,
  IconConnectionPoint2,
  IconDesktop,
  IconFile,
  IconFolderOpen,
  IconGridStroked,
  IconHome,
  IconLineChartStroked,
  IconMenu,
  IconPuzzle,
  IconSetting,
  IconShield,
  IconServer,
  IconUser,
  IconUserList,
  IconVolume2,
} from "@douyinfe/semi-icons";
import type { ReactNode } from "react";

const iconMap: Readonly<Record<string, ReactNode>> = {
  home: <IconHome />,
  menu: <IconMenu />,
  setting: <IconSetting />,
  user: <IconUser />,
  "ant-design:appstore-outlined": <IconApps />,
  "ant-design:deployment-unit-outlined": <IconBox />,
  "ant-design:home-outlined": <IconHome />,
  "ant-design:setting-outlined": <IconSetting />,
  "ant-design:user-outlined": <IconUser />,
  "ant-design:user-switch-outlined": <IconUserList />,
  "carbon:workspace": <IconDesktop />,
  "lucide:activity": <IconActivity />,
  "lucide:area-chart": <IconLineChartStroked />,
  "lucide:blocks": <IconBox />,
  "lucide:book-open": <IconArticle />,
  "lucide:box": <IconBox />,
  "lucide:brain-circuit": <IconAIStrokedLevel1 />,
  "lucide:briefcase": <IconBriefcase />,
  "lucide:building": <IconBriefcase />,
  "lucide:building-2": <IconBriefcase />,
  "lucide:calendar-range": <IconCalendarStroked />,
  "lucide:clock-3": <IconClockStroked />,
  "lucide:cpu": <IconServer />,
  "lucide:file-code": <IconCode />,
  "lucide:file-text": <IconFile />,
  "lucide:flask-conical": <IconBeaker />,
  "lucide:folder-open": <IconFolderOpen />,
  "lucide:landmark": <IconHome />,
  "lucide:layout-dashboard": <IconApps />,
  "lucide:log-in": <IconUser />,
  "lucide:megaphone": <IconVolume2 />,
  "lucide:menu": <IconMenu />,
  "lucide:network": <IconConnectionPoint2 />,
  "lucide:newspaper": <IconArticle />,
  "lucide:plug": <IconPuzzle />,
  "lucide:puzzle": <IconPuzzle />,
  "lucide:scroll-text": <IconArticle />,
  "lucide:server": <IconServer />,
  "lucide:server-cog": <IconServer />,
  "lucide:settings-2": <IconSetting />,
  "lucide:shield": <IconShield />,
  "lucide:shield-check": <IconShield />,
  "lucide:sliders-horizontal": <IconSetting />,
};

export function workbenchIcon(name?: string): ReactNode {
  return (name && iconMap[name]) || <IconGridStroked />;
}
