import type { WorkbenchRoute } from "#/router/contracts";

export const hostSupplementalRoutes: readonly WorkbenchRoute[] = [
  {
    children: [],
    componentKey: "system/message/index",
    hidden: true,
    hideInBreadcrumb: true,
    hideInTab: false,
    id: -3,
    keepAlive: false,
    name: "UserMessage",
    path: "/system/message",
    query: {},
    title: "My messages",
    titleKey: "pages.settings.message.title",
  },
  {
    children: [],
    componentKey: "profile/index",
    hidden: true,
    hideInBreadcrumb: true,
    hideInTab: false,
    id: -2,
    keepAlive: false,
    name: "UserProfile",
    path: "/profile",
    query: {},
    title: "Profile",
    titleKey: "pages.profile.tabs.basic",
  },
  {
    children: [],
    componentKey: "system/role-auth/index",
    hidden: true,
    hideInBreadcrumb: false,
    hideInTab: false,
    id: -1,
    keepAlive: false,
    name: "RoleAuthUser",
    path: "/system/role-auth/user/:id",
    permission: "system:role:query",
    query: {},
    title: "Authorized users",
    titleKey: "pages.iam.role.auth.routeTitle",
  },
];
