// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package project

import (
	"lina-plugin-linapro-tapcanvas-studio/backend/api/project"
	projectsvc "lina-plugin-linapro-tapcanvas-studio/backend/internal/service/project"
)

// ControllerV1 handles version-one project APIs.
type ControllerV1 struct {
	projectSvc projectsvc.Service
}

// NewV1 creates one project controller from its explicit service dependency.
func NewV1(projectSvc projectsvc.Service) project.IProjectV1 {
	return &ControllerV1{projectSvc: projectSvc}
}
