// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-monitor-server/backend/internal/dao/internal"
)

// serverDao is the data access object for the table plugin_linapro_monitor_server.
// You can define custom methods on it to extend its functionality as needed.
type serverDao struct {
	*internal.ServerDao
}

var (
	// Server is a globally accessible object for table plugin_linapro_monitor_server operations.
	Server = serverDao{internal.NewServerDao()}
)

// Add your custom methods and functionality below.
