// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package demo

// boolToInt converts one boolean flag into the integer shape expected by the
// sample plugin response DTOs.
func boolToInt(value bool) int {
	if value {
		return 1
	}
	return 0
}
