// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package demo

import (
	demosvc "lina-plugin-linapro-demo-source/backend/internal/service/demo"
)

// ControllerV1 is the linapro-demo-source controller.
type ControllerV1 struct {
	demoSvc demosvc.Service // demo service
}

// NewV1 creates and returns a new linapro-demo-source controller instance.
func NewV1(demoSvc demosvc.Service) *ControllerV1 {
	return &ControllerV1{demoSvc: demoSvc}
}
