// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-monitor-loginlog/backend/internal/dao/internal"
)

// loginlogDao is the data access object for the table plugin_linapro_monitor_loginlog.
// You can define custom methods on it to extend its functionality as needed.
type loginlogDao struct {
	*internal.LoginlogDao
}

var (
	// Loginlog is a globally accessible object for table plugin_linapro_monitor_loginlog operations.
	Loginlog = loginlogDao{internal.NewLoginlogDao()}
)

// Add your custom methods and functionality below.
