import type { ApiClient } from "#/api/client";
export interface JobGroup { code: string; createdAt: number | null; id: number; isDefault: number; jobCount: number; name: string; remark: string; sortOrder: number; updatedAt: number | null }
export interface JobRecord { concurrency: string; createdAt: number | null; cronExpr: string; description: string; env: string; executedCount: number; groupCode: string; groupId: number; groupName: string; handlerRef: string; id: number; isBuiltin: number; logRetentionOverride: string; maxConcurrency: number; maxExecutions: number; name: string; params: string; scope: string; seedVersion: number; shellCmd: string; status: string; stopReason: string; taskType: string; timeoutSeconds: number; timezone: string; updatedAt: number | null; workDir: string }
export interface JobLog { createdAt: number | null; durationMs: number; endAt: number | null; errMsg: string; id: number; jobId: number; jobName: string; jobSnapshot: string; nodeId: string; paramsSnapshot: string; resultJson: string; startAt: number | null; status: string; trigger: string }
export interface JobPayload { concurrency: string; cronExpr: string; description?: string; env?: Record<string, string>; groupId: number; handlerRef?: string; logRetentionOverride?: { mode: string; value: number } | null; maxConcurrency: number; maxExecutions: number; name: string; params?: Record<string, unknown>; scope: string; shellCmd?: string; status: string; taskType: string; timeoutSeconds: number; timezone: string; workDir?: string }
export interface HandlerOption { description: string; displayName: string; pluginId: string; ref: string; source: string }
export function createSystemJobApi(client: ApiClient) { return {
  cancelLog: (id: number) => client.post<void>(`job/log/${id}/cancel`), clearLogs: (query?: { beginTime?: string; endTime?: string; jobId?: number }) => client.delete<{ deleted: number }>("job/log", { query }), deleteLog: (id: number) => client.delete<void>("job/log", { query: { logIds: id } }),
  create: (input: JobPayload) => client.post<{ id: number }>("job", input), createGroup: (input: Partial<JobGroup>) => client.post<{ id: number }>("job-group", input), delete: (ids: number[]) => client.delete<void>(`job/${ids.join(",")}`), deleteGroup: (ids: number[]) => client.delete<void>(`job-group/${ids.join(",")}`),
  get: (id: number) => client.get<JobRecord>(`job/${id}`), getLog: (id: number) => client.get<JobLog>(`job/log/${id}`), handler: (ref: string) => client.get<HandlerOption & { paramsSchema: string }>(`job/handler/${encodeURIComponent(ref)}`),
  async handlers() { return (await client.get<{ list: HandlerOption[] }>("job/handler")).list; }, list: (query: Record<string, string | number | undefined>) => client.get<{ list: JobRecord[]; total: number }>("job", { query }), listGroups: (query: Record<string, string | number | undefined>) => client.get<{ list: JobGroup[]; total: number }>("job-group", { query }), listLogs: (query: Record<string, string | number | undefined>) => client.get<{ list: JobLog[]; total: number }>("job/log", { query }),
  preview: (expr: string, timezone: string) => client.get<{ times: string[] }>("job/cron-preview", { query: { expr, timezone } }), reset: (id: number) => client.post<void>(`job/${id}/reset`), trigger: (id: number) => client.post<{ logId: number }>(`job/${id}/trigger`), update: (id: number, input: JobPayload) => client.put<void>(`job/${id}`, input), updateGroup: (id: number, input: Partial<JobGroup>) => client.put<void>(`job-group/${id}`, input), updateStatus: (id: number, status: string) => client.put<void>(`job/${id}/status`, { status }),
}; }
