gfcli:
  gen:
    dao:
      - link: "pgsql:postgres:postgres@tcp(127.0.0.1:5432)/linapro?sslmode=disable"
        path: "internal"
        tables: "tapcanvas_projects,tapcanvas_chapters,tapcanvas_flows,tapcanvas_flow_mutations,tapcanvas_flow_versions"
        removePrefix: "tapcanvas_"
        importPrefix: "lina-plugin-linapro-tapcanvas-studio/backend/internal"
        descriptionTag: true
        noModelComment: true
        stdTime: true
        typeMapping:
          timestamp:
            type: "*time.Time"
            import: time
          "timestamp without time zone":
            type: "*time.Time"
            import: time
          timestamptz:
            type: "*time.Time"
            import: time
          "timestamp with time zone":
            type: "*time.Time"
            import: time
