// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-monitor-operlog/backend/internal/dao/internal"
)

// operlogDao is the data access object for the table plugin_linapro_monitor_operlog.
// You can define custom methods on it to extend its functionality as needed.
type operlogDao struct {
	*internal.OperlogDao
}

var (
	// Operlog is a globally accessible object for table plugin_linapro_monitor_operlog operations.
	Operlog = operlogDao{internal.NewOperlogDao()}
)

// Add your custom methods and functionality below.
