// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-tapcanvas-studio/backend/internal/dao/internal"
)

// chaptersDao is the data access object for the table tapcanvas_chapters.
// You can define custom methods on it to extend its functionality as needed.
type chaptersDao struct {
	*internal.ChaptersDao
}

var (
	// Chapters is a globally accessible object for table tapcanvas_chapters operations.
	Chapters = chaptersDao{internal.NewChaptersDao()}
)

// Add your custom methods and functionality below.
