// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-tapcanvas-studio/backend/internal/dao/internal"
)

// flowMutationsDao is the data access object for the table tapcanvas_flow_mutations.
// You can define custom methods on it to extend its functionality as needed.
type flowMutationsDao struct {
	*internal.FlowMutationsDao
}

var (
	// FlowMutations is a globally accessible object for table tapcanvas_flow_mutations operations.
	FlowMutations = flowMutationsDao{internal.NewFlowMutationsDao()}
)

// Add your custom methods and functionality below.
