// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-tapcanvas-studio/backend/internal/dao/internal"
)

// flowsDao is the data access object for the table tapcanvas_flows.
// You can define custom methods on it to extend its functionality as needed.
type flowsDao struct {
	*internal.FlowsDao
}

var (
	// Flows is a globally accessible object for table tapcanvas_flows operations.
	Flows = flowsDao{internal.NewFlowsDao()}
)

// Add your custom methods and functionality below.
