// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-tapcanvas-studio/backend/internal/dao/internal"
)

// flowVersionsDao is the data access object for the table tapcanvas_flow_versions.
// You can define custom methods on it to extend its functionality as needed.
type flowVersionsDao struct {
	*internal.FlowVersionsDao
}

var (
	// FlowVersions is a globally accessible object for table tapcanvas_flow_versions operations.
	FlowVersions = flowVersionsDao{internal.NewFlowVersionsDao()}
)

// Add your custom methods and functionality below.
