// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package chapter

import (
	"lina-plugin-linapro-tapcanvas-studio/backend/api/chapter"
	chaptersvc "lina-plugin-linapro-tapcanvas-studio/backend/internal/service/chapter"
)

// ControllerV1 handles version-one chapter APIs.
type ControllerV1 struct {
	chapterSvc chaptersvc.Service
}

// NewV1 creates one chapter controller from its explicit service dependency.
func NewV1(chapterSvc chaptersvc.Service) chapter.IChapterV1 {
	return &ControllerV1{chapterSvc: chapterSvc}
}
