// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package flow

import (
	"lina-plugin-linapro-tapcanvas-studio/backend/api/flow"
)

type ControllerV1 struct{}

func NewV1() flow.IFlowV1 {
	return &ControllerV1{}
}
