// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tenant

import (
	tenantapi "lina-plugin-linapro-tenant-core/backend/api/tenant"
	"lina-plugin-linapro-tenant-core/backend/internal/service/tenantplugin"
)

// ControllerV1 is the tenant-scoped linapro-tenant-core controller.
type ControllerV1 struct {
	tenantPluginSvc tenantplugin.Service
}

// NewV1 creates and returns a new tenant controller instance.
func NewV1(tenantPluginSvc tenantplugin.Service) tenantapi.ITenantV1 {
	return &ControllerV1{tenantPluginSvc: tenantPluginSvc}
}
