// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-org-core/backend/internal/dao/internal"
)

// userPostDao is the data access object for the table plugin_linapro_org_core_user_post.
// You can define custom methods on it to extend its functionality as needed.
type userPostDao struct {
	*internal.UserPostDao
}

var (
	// UserPost is a globally accessible object for table plugin_linapro_org_core_user_post operations.
	UserPost = userPostDao{internal.NewUserPostDao()}
)

// Add your custom methods and functionality below.
