// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package file

import (
	"lina-core/api/file"
	filesvc "lina-core/internal/service/file"
)

// ControllerV1 is the file controller.
type ControllerV1 struct {
	fileSvc filesvc.Service
}

// NewV1 creates and returns a new file controller instance.
func NewV1(fileSvc filesvc.Service) file.IFileV1 {
	return &ControllerV1{
		fileSvc: fileSvc,
	}
}
